require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

RSpec/DescribeClass: 
  Exclude: 
    - 'spec/features/*'
    - 'spec/requests/*'

RSpec/ExampleLength:
  Max: 20 

RSpec/MultipleExpectations:
  Max: 10
